import React, { Component } from 'react';
import { DateLocalizer } from './localizer';
interface TimeGridProps {
    events: any[];
    backgroundEvents: any[];
    resources?: any[];
    step?: number;
    timeslots?: number;
    range?: any[];
    min: any;
    max: any;
    getNow: (...args: any[]) => any;
    scrollToTime: any;
    enableAutoScroll?: boolean;
    showMultiDayTimes?: boolean;
    rtl?: boolean;
    resizable?: boolean;
    width?: number;
    accessors: any;
    components: any;
    getters: any;
    localizer: DateLocalizer;
    eventOffset?: number;
    allDayMaxRows?: number;
    selected?: object;
    selectable?: true | false | 'ignoreEvents';
    longPressThreshold?: number;
    onNavigate?: (...args: unknown[]) => unknown;
    onSelectSlot?: (...args: unknown[]) => unknown;
    onSelectEnd?: (...args: unknown[]) => unknown;
    onSelectStart?: (...args: unknown[]) => unknown;
    onSelectEvent?: (...args: unknown[]) => unknown;
    onShowMore?: (...args: unknown[]) => unknown;
    onDoubleClickEvent?: (...args: unknown[]) => unknown;
    onKeyPressEvent?: (...args: unknown[]) => unknown;
    onDrillDown?: (...args: unknown[]) => unknown;
    getDrilldownView: (...args: unknown[]) => unknown;
    dayLayoutAlgorithm?: unknown;
    showAllEvents?: boolean;
    doShowMoreDrillDown?: boolean;
    popup?: boolean;
    handleDragStart?: (...args: unknown[]) => unknown;
    popupOffset?: number | {
        x?: number;
        y?: number;
    };
}
export default class TimeGrid extends Component<TimeGridProps, any> {
    static defaultProps: {
        step: number;
        timeslots: number;
    };
    private containerRef;
    private contentRef;
    private gutterRef;
    private scrollRef;
    private _scrollRatio;
    private _updatingOverflow;
    private rafHandle;
    private measureGutterAnimationFrameRequest;
    private slots;
    private _selectTimer;
    private _pendingSelection;
    constructor(props: any);
    getSnapshotBeforeUpdate(): any;
    componentDidMount(): void;
    handleScroll: (e: any) => void;
    handleResize: () => void;
    componentWillUnmount(): void;
    componentDidUpdate(): void;
    handleKeyPressEvent: (event: any, e: React.SyntheticEvent) => void;
    handleSelectEvent: (event: any, e: React.SyntheticEvent) => void;
    handleDoubleClickEvent: (event: any, e: React.SyntheticEvent) => void;
    handleShowMore: (events: any, date: any, cell: any, slot: any, target: any) => void;
    handleSelectAllDaySlot: (slots: any, slotInfo: any) => void;
    renderEvents(range: any, events: any, backgroundEvents: any, now: any): any;
    render(): React.JSX.Element;
    renderOverlay(): React.JSX.Element;
    overlayDisplay: () => void;
    clearSelection(): void;
    measureGutter(): void;
    applyScroll(): void;
    calculateScroll(props?: Readonly<TimeGridProps>): void;
    checkOverflow: () => void;
    memoizedResources: import("memoize-one").MemoizedFn<(this: any, resources: any, accessors: any) => {
        map(fn: any): any;
        groupEvents(events: any): Map<any, any>;
    }>;
}
export {};
