export { milliseconds, seconds, minutes, hours, month, startOf, endOf, add, eq, neq, gte, gt, lte, lt, inRange, min, max, } from 'date-arithmetic';
export declare function monthsInYear(year: any): any[];
export declare function firstVisibleDay(date: any, localizer: any): any;
export declare function lastVisibleDay(date: any, localizer: any): any;
export declare function visibleDays(date: any, localizer: any): any[];
export declare function ceil(date: any, unit: any): any;
export declare function range(start: any, end: any, unit?: string): any[];
export declare function merge(date: any, time: any): any;
export declare function eqTime(dateA: any, dateB: any): boolean;
export declare function isJustDate(date: any): boolean;
export declare function duration(start: any, end: any, unit: any, firstOfWeek: any): number;
export declare function diff(dateA: any, dateB: any, unit: any): number;
export declare function total(date: any, unit: any): number;
export declare function week(date: any): number;
export declare function today(): any;
export declare function yesterday(): any;
export declare function tomorrow(): any;
