import { DateTime } from 'luxon'

const now = DateTime.now()

export default [
  {
    id: 1,
    title: 'Long Event',
    start: DateTime.fromObject({ year: 2015, month: 4, day: 7 }).toJSDate(),
    end: DateTime.fromObject({ year: 2015, month: 4, day: 10 }).toJSDate(),
  },

  {
    id: 2,
    title: 'DTS STARTS',
    start: DateTime.fromObject({ year: 2016, month: 3, day: 13 }).toJSDate(),
    end: DateTime.fromObject({ year: 2016, month: 3, day: 20 }).toJSDate(),
  },

  {
    id: 3,
    title: 'DTS ENDS',
    start: DateTime.fromObject({ year: 2016, month: 11, day: 6 }).toJSDate(),
    end: DateTime.fromObject({ year: 2016, month: 11, day: 13 }).toJSDate(),
  },

  {
    id: 4,
    title: 'Some Event',
    start: DateTime.fromObject({ year: 2015, month: 4, day: 9 }).toJSDate(),
    end: DateTime.fromObject({ year: 2015, month: 4, day: 9 }).toJSDate(),
    allDay: true,
  },

  {
    id: 92,
    title: 'Some Other Event',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 9,
      hour: 8,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 10,
      hour: 11,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 5,
    title: 'Conference',
    start: DateTime.fromObject({ year: 2015, month: 4, day: 11 }).toJSDate(),
    end: DateTime.fromObject({ year: 2015, month: 4, day: 13 }).toJSDate(),
    desc: 'Big conference for important people',
  },
  {
    id: 6,
    title: 'Meeting',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 10,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 12,
      minute: 30,
    }).toJSDate(),
    desc: 'Pre-meeting meeting, to prepare for the meeting',
  },
  {
    id: 7,
    title: 'Lunch',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 12,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 13,
    }).toJSDate(),
    desc: 'Power lunch',
  },
  {
    id: 8,
    title: 'Meeting',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 14,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 15,
    }).toJSDate(),
  },
  {
    id: 9,
    title: 'Happy Hour',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 17,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 17,
      minute: 30,
    }).toJSDate(),
    desc: 'Most important meal of the day',
  },
  {
    id: 10,
    title: 'Dinner',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 20,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 12,
      hour: 21,
    }).toJSDate(),
  },
  {
    id: 11,
    title: 'Planning Meeting with Paige',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 8,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 10,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 11.1,
    title: 'Inconvenient Conference Call',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 9,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 12,
    }).toJSDate(),
  },
  {
    id: 11.2,
    title: "Project Kickoff - Lou's Shoes",
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 11,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 14,
    }).toJSDate(),
  },
  {
    id: 11.3,
    title: 'Quote Follow-up - Tea by Tina',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 15,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 13,
      hour: 16,
    }).toJSDate(),
  },
  {
    id: 12,
    title: 'Late Night Event',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 17,
      hour: 19,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 18,
      hour: 2,
    }).toJSDate(),
  },
  {
    id: 12.5,
    title: 'Late Same Night Event',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 17,
      hour: 19,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 17,
      hour: 23,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 13,
    title: 'Multi-day Event',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 20,
      hour: 19,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 22,
      hour: 2,
    }).toJSDate(),
  },
  {
    id: 14,
    title: 'Today',
    start: DateTime.now().minus({ hours: 3 }).toJSDate(),
    end: DateTime.now().plus({ hours: 3 }).toJSDate(),
  },
  {
    id: 15,
    title: 'Point in Time Event',
    start: now.toJSDate(),
    end: now.toJSDate(),
  },
  {
    id: 16,
    title: 'Video Record',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 15,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 19,
    }).toJSDate(),
  },
  {
    id: 17,
    title: 'Dutch Song Producing',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 16,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 20,
    }).toJSDate(),
  },
  {
    id: 18,
    title: 'Itaewon Meeting',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 16,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 17,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 19,
    title: 'Online Coding Test',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 17,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 20,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 20,
    title: 'An overlapped Event',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 17,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 18,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 21,
    title: 'Phone Interview',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 17,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 18,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 22,
    title: 'Cooking Class',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 17,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 19,
    }).toJSDate(),
  },
  {
    id: 23,
    title: 'Go to the gym',
    start: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 18,
      minute: 30,
    }).toJSDate(),
    end: DateTime.fromObject({
      year: 2015,
      month: 4,
      day: 14,
      hour: 20,
    }).toJSDate(),
  },
  {
    id: 24,
    title: 'DST ends on this day (Europe)',
    start: DateTime.fromObject({ year: 2022, month: 10, day: 30 }).toJSDate(),
    end: DateTime.fromObject({
      year: 2022,
      month: 10,
      day: 30,
      hour: 4,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 25,
    title: 'DST ends on this day (America)',
    start: DateTime.fromObject({ year: 2022, month: 11, day: 6 }).toJSDate(),
    end: DateTime.fromObject({
      year: 2022,
      month: 11,
      day: 6,
      hour: 4,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 26,
    title: 'DST starts on this day (America)',
    start: DateTime.fromObject({ year: 2023, month: 3, day: 12 }).toJSDate(),
    end: DateTime.fromObject({
      year: 2023,
      month: 3,
      day: 12,
      hour: 4,
      minute: 30,
    }).toJSDate(),
  },
  {
    id: 27,
    title: 'DST starts on this day (Europe)',
    start: DateTime.fromObject({ year: 2023, month: 3, day: 26 }).toJSDate(),
    end: DateTime.fromObject({
      year: 2023,
      month: 3,
      day: 26,
      hour: 4,
      minute: 30,
    }).toJSDate(),
  },
]
